<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img src="http://ebizmarts.com/extension-logo.php?<?php echo $this->getPxParams(); ?>"/><br><br>
        <div style="padding-left: 30px;">
            <p> <strong style="color:#EA7601;">MageMonkey v<?php echo $this->getVersion() ?> by</strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a></p>
            <p>Need help? See our <a href="http://wiki.ebizmarts.com/installation" target="_blank">Wiki</a> or browse our <a href="http://ebizmarts.com/forums/view/1" target="_blank">support forums</a> Got feedback? <a href="mailto:info@ebizmarts.com?Subject=Mandrill Version <?php echo $this->getVersion()?>">Email us</a></p>
            <p>You can find more extension in our <a href="http://store.ebizmarts.com" target="_blank">Store</a></p>
        </div>
    </h4>
</div>